version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=RetoUCUbd
      - POSTGRES_USER=UCUser
      - POSTGRES_PASSWORD=pass
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=RetoUCUbd
      - POSTGRES_USER=RetoUCUbd
      - POSTGRES_PASSWORD=pass
    depends_on:
      - db
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    volumes:
      - DC_Redis_2:/var/lib/redis/data

volumes:
  DC_Postgres_2:
  DC_Redis_2: